version: 1
epochs: 80
batch_size: 256
criterion: cross_entropy
label_smoothing: 0.1
metrics: [top1, top2]

onecycle:
  enabled: true
  max_lr: 0.003
  pct_start: 0.1
  anneal_strategy: cos
  div_factor: 25.0
  final_div_factor: 10000.0

train:
  amp: true
  compile: true
  channels_last: true
  cudnn_benchmark: true
  tf32: true
  log_interval: 50
  ckpt_interval: 1
  ckpt_keep_last: 3